// PRODUCTS_VARIABLES
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT_ID = 'GET_PRODUCT_ID'

export const ADD_PRODUCT_REVIEW = 'ADD_PRODUCT_REVIEW'
export const SHOW_PRODUCT_REVIEW_FORM = 'SHOW_PRODUCT_REVIEW_FORM'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const COPY_PRODUCT = 'COPY_PRODUCT'

export const GET_PRODUCT_IMG = 'GET_PRODUCT_IMG'


// APP VARIABLES 
// basket
export const GET_PRODUCTS_IN_BASKET = 'GET_PRODUCTS_IN_BASKET'
export const ADD_PRODUCTS_IN_BASKET = 'ADD_PRODUCTS_IN_BASKET'
export const REMOVE_PRODUCTS_IN_BASKET = 'REMOVE_PRODUCTS_IN_BASKET'
export const DELETE_PRODUCTS_FROM_BASKET = 'DELETE_PRODUCTS_FROM_BASKET'
export const DELETE_ALL_FROM_BASKET = 'DELETE_ALL_FROM_BASKET'
export const GET_DATA_FROM_ORDER_FORM = 'GET_DATA_FROM_ORDER_FORM'
export const HIDE_ORDER_SUCCESS = 'HIDE_ORDER_SUCCESS'
export const HIDE_MODAL_BASKET_IS_EMPTY = 'HIDE_MODAL_BASKET_IS_EMPTY'
export const SEND_ORDER_DATA = 'SEND_ORDER_DATA'

// pagination
export const GET_PAGINATION_PAGE = 'GET_PAGINATION_PAGE'

// categories
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORY = 'GET_CATEGORY'


// ADMIN VARIABLES 
export const ADMIN_MODAL_FILTER = 'ADMIN_MODAL_FILTER'
export const ADMIN_VIEW_CARDS = 'ADMIN_VIEW_CARDS'
export const ADMIN_MODAL_CONTACT_WITH = 'ADMIN_MODAL_CONTACT_WITH'
export const ADMIN_MODAL_ADD_PRODUCT = 'ADMIN_MODAL_ADD_PRODUCT'
export const ADMIN_MODAL_EDIT_PRODUCT = 'ADMIN_MODAL_EDIT_PRODUCT'
export const ADMIN_MODAL_SUCCESS = 'ADMIN_MODAL_SUCCESS'
export const ADMIN_INFO_PRODUCT = 'ADMIN_INFO_PRODUCT'
export const ADMIN_INFO_ORDER_PRODUCT = 'ADMIN_INFO_ORDER_PRODUCT'
export const ADMIN_SHOW_ANSWER_FORM = 'ADMIN_SHOW_ANSWER_FORM'
export const ADMIN_SHOW_ANSWER = 'ADMIN_SHOW_ANSWER'
export const ADMIN_SHOW_MODAL_CONTACT = 'ADMIN_SHOW_MODAL_CONTACT'
export const ADMIN_GET_MESSAGE_TEXT_FROM_FORM = 'ADMIN_GET_MESSAGE_TEXT_FROM_FORM'

export const ADMIN_GET_PROFILE_DATA = 'ADMIN_GET_PROFILE_DATA'

export const ADMIN_GET_ORDERS = 'ADMIN_GET_ORDERS'